language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: angular-hw-jira
  api_key:
    secure: 1/p0H1HX2qVav5UZ0ivxPlbr87bGBLWG7Kng9Q8A7vIWjtYRxcrgVkma5IXDgk3pGj2rWvS1o7U0smvcAzJuvX7fBdpODE+lrNuzLgfdb60lu/E2iRxk1w0r/e/6vOGPi4WRiVKtIIBWDEz8pZlXw62DVFRwz7uVCMvx7uC6uWXoxOJz+SeXUshj1Zj0nduP/T1p0qGK9xW25cas/1IMZkTwKH5UxXT6TDIvfvhwj6v3OtkBIUL4qEnDuHr+7tb1k3pdhQuP4hT8vxe/FWxQhHXeldB4AjTrvVJoXxMstwB5AZvMwZDBXP9RlqhFJ8bZbu86JqI6rQtNNcxibJN/9xSJiVWqJ6f1YpszLFa2G+ZYGPwhQ/vT+un2AJS/J6GGTsBOR2u91h2H+uqs+/4GGxetkRC82fTNgKxHEAqmM8YP37dC4DhVlwcyUkPlhLdNT6aDnHsfuoGDiC4oUnrAIGdQkzX0OEGeJLU1+et5OqqutY8nKWNnFcaVLfiNUFeGkS1TRzaANK8hwN+IFVOONphQIZpwOmUFqasezpByugKlHIGEQoxjpvFmUDF2vkii+pyvjkTBX1/K4/zEYswnaAQW5Jj5CDNQj4jQWqnVVvss2at7AdK+pgWt2UsyQDII/CDh0eUGssml6HW8r7mQPexTMf6Zo412L/hsKtGgIk8=
